=== shcherbak/jargon/api/mdm-api/schema/mdm-facility-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Facility",
  "description": "Facility Type definition",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "description": "The unique identifier of the facility"
    },
    "gid": {
      "description": "Global document ID UUID4",
      "type": "string",
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
    },
    "facility_code": {
      "type": "string",
      "description": "The unique autogenerated code"
    },
    "version_num": {
      "type": "integer",
      "description": "version number"
    },
    "display_name": {
      "type": "string",
      "description": "Human readable facility name"
    },
    "document_date": {
      "type": "string",
      "pattern": "20[0-9]{2}-[0-1][0-9]-[0-3][0-9]"
    },
    "parent_facility_code": {
      "type": "string",
      "description": "Parent Facility code"
    },
    "facility_type": {
      "description": "Facility hierarchy scope",
      "type": "string",
      "enum": [
        "ENTERPRISE",
        "SITE",
        "AREA",
        "LINE",
        "ZONE"
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "id",
    "gid",
    "facility_code",
    "display_name",
    "document_date",
    "parent_facility_code",
    "facility_type"
  ]
}

=== shcherbak/jargon/raml/json/mdm-facilities-example.json
[
  {
    "id": 123,
    "gid": "b3dbaf2c-3f1c-11e7-b691-d4bed939923a",
    "facility_code": "SZN-A10-AB1AA0",
    "display_name": "Storage Zone of Area ARE-M10-ZX1BB0",
    "document_date": "2018-01-01",
    "parent_facility_code": "ARE-M10-ZX1BB0",
    "facility_type": "ZONE"
  },
  {
    "id": 456,
    "gid": "160fd11a-4011-11e7-9b12-d4bed939923a",
    "facility_code": "LNE-A11-AB1AA1",
    "display_name": "Production Line of Area ARE-M10-ZX1BB0",
    "document_date": "2018-01-01",
    "parent_facility_code": "ARE-M10-ZX1BB0",
    "facility_type": "LINE"
  }
]
